http:
  routers:
    surrealdb:
      rule: PathPrefix(`/sb/surreal`)
      service: surrealdb@file
      middlewares:
        - strip-sb-prefix
        - strip-surreal-prefix

  services:
    surrealdb:
      loadBalancer:
        servers:
          - url: "http://db:8080/"
        healthCheck:
          path: /health
          interval: "10s"

  middlewares:
    strip-surreal-prefix:
      stripPrefix:
        prefixes:
          - "/surreal"
